=== mdtheslayer/architect/lud/improve-lud227/message-example/json-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$ref": "#/definitions/ThinkMessage",
	"definitions": {
		"NewResults": {
			"$ref": "#/definitions/AbstractResults",
			"description": "Новый результат"
		},
		"OldResults": {
			"$ref": "#/definitions/AbstractResults",
			"description": "Аннулированный результат"
		},
		"AbstractResults": {
			"description": "Массив с контентом в рамках  документа",
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"version": {
						"type": [
							"string",
							"null"
						]
					},
					"login": {
						"type": [
							"string",
							"null"
						]
					},
					"documentCommittedDate": {
						"type": [
							"string",
							"null"
						]
					},
					"composition_": {
						"$ref": "#/definitions/Composition"
					}
				},
				"required": [
					"composition_"
				]
			}
		},
		"Composition": {
			"description": "Контент документа(Композиция)",
			"type": "object",
			"properties": {
				"content": {
					"$ref": "#/definitions/Content"
				},
				"context": {
					"$ref": "#/definitions/Context"
				}
			},
			"required": [
				"content",
				"context"
			]
		},
		"ThinkMessage": {
			"description": "valiadtion message",
			"type": "object",
			"properties": {
				"domain": {
					"description": "Домен ",
					"type": "string"
				},
				"ehrUid": {
					"description": "Юид",
					"type": "string"
				},
				"operationType": {
					"description": "Тип операции",
					"type": "string",
					"enum": [
						"create",
						"update",
						"delete"
					]
				},
				"eventName": {
					"description": "Триггер",
					"type": "string"
				},
				"compositionId": {
					"description": "Идентификатор композиции",
					"type": "string"
				},
				"newResults": {
					"$ref": "#/definitions/NewResults"
				},
				"oldResults": {
					"$ref": "#/definitions/OldResults"
				},
				"comment": {
					"description": "Комментарий",
					"type": "string"
				}
			},
			"required": [
				"operationType",
				"eventName",
				"compositionId"
			],
			"additionalProperties": false,
			"oneOf": [
				{
					"properties": {
						"operationType": {
							"type": "string",
							"enum": [
								"create",
								"update"
							]
						}
					},
					"required": [
						"newResults"
					]
				},
				{
					"properties": {
						"operationType": {
							"type": "string",
							"enum": [
								"delete"
							]
						}
					},
					"required": [
						"oldResults"
					]
				}
			]
		},
		"Content": {
			"type": "array",
			"minItems": 1,
			"items": {
				"type": "object"
			},
			"contains": {
				"$ref": "#/definitions/CorrectDiagnosis"
			},
			"minContains": 1
		},
		"Context": {
			"type": "object",
			"properties": {
				"other_context": {
					"type": "object",
					"properties": {
						"items": {
							"type": "array",
							"minItems": 1,
							"items": {
								"type": "object",
								"minItems": 1,
								
                                "minContains":1,
								"required": [
									"items"
								]
							},
                            "contains": {"$ref":"#/definitions/CorrectOtherContext"}  
						}
					},
					"required": [
						"items"
					]
				}
			},
			"required": [
				"other_context"
			]
		},
		"CorrectOtherContext": {
			"type": "object",
			"properties": {
				"items": {
					"type": "array",
					"minItems": 1,
					"items": {
						"type": "object"
					},
					"allOf": [
						{
							"contains": {
								"$ref": "#/definitions/PatientId"
							}
						},
						{
							"contains": {
								"$ref": "#/definitions/DocumentId"
							}
						}
					]
				}
			}
		},
		"CorrectDiagnosis": {
			"type": "object",
			"properties": {
				"name": {
					"type": "object",
					"properties": {
						"value": {
							"type": "string",
							"enum": [
								"Диагноз",
								"Диагноз при выписке",
								"Диспансерное наблюдение",
								"Выписка из ИБ",
								"Диагноз при выписке из санаторно-курортной организации (основное заболевание)",
								"Состояние здоровья по результатам проведения настоящего профилактического осмотра/диспансеризации",
                                "Диагноз наблюдения пациента"
							]
						}
					},
					"required": [
						"value"
					]
				}
			},
			"required": [
				"name"
			]
		},
		"DocumentId": {
			"type": "object",
			"properties": {
				"name": {
					"type": "object",
					"properties": {
						"value": {
							"type": "string",
							"pattern": "ИД документа"
						}
					},
					"required": [
						"value"
					]
				},
				"value": {
					"type": "object",
					"properties": {
						"id": {
							"type": "string"
						}
					},
					"required": [
						"id"
					]
				}
			},
			"required": [
				"name",
				"value"
			]
		},
		"PatientId": {
			"type": "object",
			"properties": {
				"name": {
					"type": "object",
					"properties": {
						"value": {
							"type": "string",
							"pattern": "ИД пациента"
						}
					},
					"required": [
						"value"
					]
				},
				"value": {
					"type": "object",
					"properties": {
						"id": {
							"type": "string"
						}
					},
					"required": [
						"id"
					]
				}
			},
			"required": [
				"name",
				"value"
			]
		}
	}
}

=== mdtheslayer/architect/lud/improve-lud227/message-example/t_cancer_registry_oncology_epicrisis-1example.json
{
	"domain": "default",
	"ehrUid": "6bf341c3-5dc0-401a-bbec-ab58bca5eba3",
	"operationType": "create",
	"eventName": "t_preventive_care_pediatrist_examinationQueue",
	"compositionId": "fb676c5c-ad9f-40c6-b418-ff7d1d5e63ee::default::1",
	"newResults":  [
    {
      "version_": "openEHR-EHR-COMPOSITION.t_cancer_registry_oncology_epicrisis.v1",
      "login": "DAzimova",
      "documentCommittedDate": "2021-10-30T09:04:47.598188+03:00",
      "composition_": {
        "@class": "COMPOSITION",
        "name": {
          "@class": "DV_TEXT",
          "value": "Выписной онкологический эпикриз"
        },
        "uid": {
          "@class": "OBJECT_VERSION_ID",
          "value": "0a1b7996-7b49-4d69-a804-a87d5384203c::default::2"
        },
        "archetype_details": {
          "@class": "ARCHETYPED",
          "archetype_id": {
            "@class": "ARCHETYPE_ID",
            "value": "openEHR-EHR-COMPOSITION.report.v1"
          },
          "template_id": {
            "@class": "TEMPLATE_ID",
            "value": "openEHR-EHR-COMPOSITION.t_cancer_registry_oncology_epicrisis.v1"
          },
          "rm_version": "1.0.4"
        },
        "archetype_node_id": "openEHR-EHR-COMPOSITION.report.v1",
        "language": {
          "@class": "CODE_PHRASE",
          "terminology_id": {
            "@class": "TERMINOLOGY_ID",
            "value": "ISO_639-1"
          },
          "code_string": "ru"
        },
        "territory": {
          "@class": "CODE_PHRASE",
          "terminology_id": {
            "@class": "TERMINOLOGY_ID",
            "value": "ISO_3166-1"
          },
          "code_string": "RU"
        },
        "category": {
          "@class": "DV_CODED_TEXT",
          "value": "event",
          "defining_code": {
            "@class": "CODE_PHRASE",
            "terminology_id": {
              "@class": "TERMINOLOGY_ID",
              "value": "openehr"
            },
            "code_string": "433"
          }
        },
        "composer": {
          "@class": "PARTY_IDENTIFIED",
          "external_ref": {
            "@class": "PARTY_REF",
            "id": {
              "@class": "GENERIC_ID",
              "value": "17041554238",
              "scheme": "undefined"
            },
            "namespace": "Парус",
            "type": "ANY"
          },
          "name": "Азимова Дилфуза Исроиловна"
        },
        "context": {
          "@class": "EVENT_CONTEXT",
          "start_time": {
            "@class": "DV_DATE_TIME",
            "value": "2021-10-30T09:03:39+03:00"
          },
          "end_time": {
            "@class": "DV_DATE_TIME",
            "value": "2021-10-30T09:04:44+03:00"
          },
          "setting": {
            "@class": "DV_CODED_TEXT",
            "value": "other care",
            "defining_code": {
              "@class": "CODE_PHRASE",
              "terminology_id": {
                "@class": "TERMINOLOGY_ID",
                "value": "openehr"
              },
              "code_string": "238"
            }
          },
          "other_context": {
            "@class": "ITEM_TREE",
            "name": {
              "@class": "DV_TEXT",
              "value": "*Tree(en)"
            },
            "archetype_node_id": "at0001",
            "items": [
              {
                "@class": "CLUSTER",
                "name": {
                  "@class": "DV_TEXT",
                  "value": "Подробности контекста"
                },
                "archetype_details": {
                  "@class": "ARCHETYPED",
                  "archetype_id": {
                    "@class": "ARCHETYPE_ID",
                    "value": "openEHR-EHR-CLUSTER.composition_context_details_simi.v0"
                  },
                  "rm_version": "1.0.4"
                },
                "archetype_node_id": "openEHR-EHR-CLUSTER.composition_context_details_simi.v0",
                "items": [
                  {
                    "@class": "ELEMENT",
                    "name": {
                      "@class": "DV_TEXT",
                      "value": "ИД события"
                    },
                    "archetype_node_id": "at0035",
                    "value": {
                      "@class": "DV_IDENTIFIER",
                      "issuer": "undefined",
                      "assigner": "undefined",
                      "id": "7030",
                      "type": "Идентификатор События"
                    }
                  },
                  {
                    "@class": "ELEMENT",
                    "name": {
                      "@class": "DV_TEXT",
                      "value": "ИД документа"
                    },
                    "archetype_node_id": "at0073",
                    "value": {
                      "@class": "DV_IDENTIFIER",
                      "issuer": "undefined",
                      "assigner": "undefined",
                      "id": "cc620f17-7573-42ca-9981-df63c9dda596",
                      "type": "Идентификатор документа СИМИ"
                    }
                  },
                  {
                    "@class": "ELEMENT",
                    "name": {
                      "@class": "DV_TEXT",
                      "value": "ИД пациента"
                    },
                    "archetype_node_id": "at0075",
                    "value": {
                      "@class": "DV_IDENTIFIER",
                      "issuer": "undefined",
                      "assigner": "undefined",
                      "id": "20534639",
                      "type": "Идентификатор пациента"
                    }
                  },
                  {
                    "@class": "CLUSTER",
                    "name": {
                      "@class": "DV_TEXT",
                      "value": "Автор информации"
                    },
                    "archetype_node_id": "at0036",
                    "items": [
                      {
                        "@class": "ELEMENT",
                        "name": {
                          "@class": "DV_TEXT",
                          "value": "Идентификатор исполнения должности медработника"
                        },
                        "archetype_node_id": "at0092",
                        "value": {
                          "@class": "DV_IDENTIFIER",
                          "issuer": "undefined",
                          "assigner": "undefined",
                          "id": "13303659",
                          "type": "EMIAS"
                        }
                      },
                      {
                        "@class": "ELEMENT",
                        "name": {
                          "@class": "DV_TEXT",
                          "value": "Наименование должности"
                        },
                        "archetype_node_id": "at0037",
                        "value": {
                          "@class": "DV_TEXT",
                          "value": "Врач - онколог"
                        }
                      },
                      {
                        "@class": "ELEMENT",
                        "name": {
                          "@class": "DV_TEXT",
                          "value": "Наименование структурного подразделения"
                        },
                        "archetype_node_id": "at0038",
                        "value": {
                          "@class": "DV_TEXT",
                          "value": "Онкологическое отделение"
                        }
                      },
                      {
                        "@class": "ELEMENT",
                        "name": {
                          "@class": "DV_TEXT",
                          "value": "Наименование филиала"
                        },
                        "archetype_node_id": "at0039",
                        "value": {
                          "@class": "DV_TEXT",
                          "value": "Городская больница № 3"
                        }
                      },
                      {
                        "@class": "ELEMENT",
                        "name": {
                          "@class": "DV_TEXT",
                          "value": "Наименование юридического лица"
                        },
                        "archetype_node_id": "at0040",
                        "value": {
                          "@class": "DV_TEXT",
                          "value": "ГБ №3"
                        }
                      }
                    ]
                  },
                  {
                    "@class": "CLUSTER",
                    "name": {
                      "@class": "DV_TEXT",
                      "value": "Структура медицинской организации"
                    },
                    "archetype_node_id": "at0014",
                    "items": [
                      {
                        "@class": "ELEMENT",
                        "name": {
                          "@class": "DV_TEXT",
                          "value": "ИД объекта"
                        },
                        "archetype_node_id": "at0015",
                        "value": {
                          "@class": "DV_IDENTIFIER",
                          "issuer": "issuer",
                          "assigner": "assigner",
                          "id": "10449178",
                          "type": "type"
                        }
                      },
                      {
                        "@class": "ELEMENT",
                        "name": {
                          "@class": "DV_TEXT",
                          "value": "Тип объекта"
                        },
                        "archetype_node_id": "at0018",
                        "value": {
                          "@class": "DV_CODED_TEXT",
                          "value": "амбулаторно-поликлинический центр",
                          "defining_code": {
